import { useCallback } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useForm } from "react-hook-form";
import { UserInput, UserInputSchema } from "../lib/graphql";
import { zodResolver } from "@hookform/resolvers/zod";
import { TextInput } from "../components/form";
import { Button, Stack } from "@chakra-ui/react";

const Home: NextPage = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
    clearErrors,
  } = useForm<UserInput>({
    resolver: zodResolver(UserInputSchema()),
    reValidateMode: "onSubmit",
  });
  const onSubmit = useCallback((data: UserInput) => {
    console.log(data);
  }, []);
  const handleChange = useCallback(() => clearErrors(), [clearErrors]);
  return (
    <div className={styles.container}>
      <Head>
        <title>Form validation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <Stack spacing={10}>
            <TextInput
              placeholder="email"
              label="email"
              errorMessage={errors.email?.message}
              {...register("email")}
              onChange={handleChange}
            />
            <TextInput
              placeholder="message"
              label="message"
              errorMessage={errors.message?.message}
              {...register("message")}
              onChange={handleChange}
            />

            <Button type="submit" colorScheme="blue">
              Submit
            </Button>
          </Stack>
        </form>
      </main>
    </div>
  );
};

export default Home;
