import { useCallback } from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useForm } from "react-hook-form";
import { UserInput, UserInputSchema } from "../lib/graphql";
import { zodResolver } from "@hookform/resolvers/zod";

const Home: NextPage = () => {
  const { register, handleSubmit } = useForm<UserInput>({
    resolver: zodResolver(UserInputSchema()),
  });
  const onSubmit = useCallback((data: UserInput) => {
    console.log(data);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form onSubmit={handleSubmit(onSubmit)}>
          <input type="email" placeholder="email" {...register("email")} />
          <input type="text" placeholder="name" {...register("message")} />

          <input type="submit" />
        </form>
      </main>
    </div>
  );
};

export default Home;
